language: haskell
ghc: '7.10'

install:
  - cabal update
  - cabal install cabal-install
  - cabal install --only-dependencies --enable-tests

sudo: false
addons:
  apt:
    packages:
    - ghc-7.10.3
    - openjdk-8-jdk

notifications:
  email:
    - samir@noodlesandwich.com
