language: haskell
ghc: 7.8

before_install:
    - sudo apt-add-repository -y ppa:openjdk-r/ppa
    - sudo apt-get update
    - sudo apt-get install openjdk-8-jdk
    - sudo update-java-alternatives -s java-1.8.0-openjdk-amd64

notifications:
    email:
        - samir@noodlesandwich.com
